apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jmeter-worker
  name: jmeter-worker
  namespace: jmeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jmeter-worker
  template:
    metadata:
      labels:
        app: jmeter-worker
    spec:
      containers:
        - name: jmeter-worker
          image: thclpr/jmeter-worker:latest
          imagePullPolicy: Always
          env:
          - name: SSL_DISABLED
            value: "true"
          livenessProbe:
            tcpSocket:
              port: 1099
            initialDelaySeconds: 60
            periodSeconds: 5
          ports:
          - containerPort: 1099
            name: server-port
            protocol: TCP
          - containerPort: 60001
            name: rmi-local-port
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 1099
            initialDelaySeconds: 30
            periodSeconds: 5