kind: Service
apiVersion: v1
metadata:
  labels:
    app: jmeter-worker
  name: jmeter-worker
  namespace: jmeter
spec:
  selector:
    app: jmeter-worker
  clusterIP: None
  ports:
  - name: server-port
    protocol: TCP
    port: 1099
    targetPort: 1099
  - name: rmi-local-port
    protocol: TCP
    port: 60001
    targetPort: 60001
